package com.polypilot.wallet.service;


import com.polypilot.auth.entity.UserIdentity;
import com.polypilot.auth.enums.IdentityType;
import com.polypilot.auth.repository.UserIdentityRepository;
import com.polypilot.wallet.client.AuthServiceClient;
import com.polypilot.wallet.dto.L2Credentials;
import com.polypilot.wallet.dto.WalletConnectRequest;
import com.polypilot.wallet.entity.WalletCredential;
import com.polypilot.wallet.repository.WalletCredentialRepository;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.util.Locale;
import java.util.UUID;

@Service
@AllArgsConstructor
public class WalletService {

    private final AuthServiceClient          authServiceClient;
    private final EncryptionService          encryption;
    private final WalletCredentialRepository repository;
    private final UserIdentityRepository     identityRepository;

    /**
     * Verify a signed {@code ClobAuth} message and connect the wallet.
     *
     * <p>SIWE login already proved the caller controls the wallet address, so there
     * is no separate challenge round-trip: the authenticated {@code userId} (JWT
     * {@code sub}) is trusted. As defence in depth the request address must still
     * match the caller's {@code ETH_WALLET} identity — a logged-in user may only
     * connect credentials for the wallet they authenticated with.
     *
     * <p>{@code request.timestamp} and {@code request.nonce} are generated by the
     * client as part of the {@code ClobAuth} message sent to Polymarket for
     * verification; the orchestrator only forwards them to the auth-service.
     */
    public void connectWallet(WalletConnectRequest request, UUID userId) {
        assertWalletBelongsToUser(userId, request.getAddress());

        L2Credentials credentials = authServiceClient.verifyAndDerive(request);

        persistCredentials(userId, request.getAddress(), credentials);
    }

    /**
     * Used by the trading engine to load decrypted credentials before signing orders.
     * Returns null if the user has not connected a wallet yet.
     */
    public L2Credentials loadCredentials(UUID userId) {
        return repository.findByUserId(userId)
                .map(row -> new L2Credentials(
                        encryption.decrypt(row.getApiKeyEnc()),
                        encryption.decrypt(row.getSecretEnc()),
                        encryption.decrypt(row.getPassphraseEnc())
                ))
                .orElse(null);
    }

    // private helpers

    /**
     * Assert the address in the request is the one the authenticated user signed in
     * with. Wallet identities store the {@code 0x…} address lower-cased (see
     * {@link com.polypilot.auth.siwe.SiweService}), so the request address is
     * normalised the same way before comparison.
     */
    private void assertWalletBelongsToUser(UUID userId, String requestAddress) {
        String normalized = requestAddress == null
                ? null
                : requestAddress.toLowerCase(Locale.ROOT);

        boolean owned = identityRepository.findByUserId(userId).stream()
                .filter(identity -> identity.getType() == IdentityType.ETH_WALLET)
                .map(UserIdentity::getIdentifier)
                .anyMatch(walletAddress -> walletAddress.equals(normalized));

        if (!owned) {
            throw new ResponseStatusException(
                    HttpStatus.FORBIDDEN,
                    "Wallet address is not registered to the authenticated account"
            );
        }
    }

    private void persistCredentials(UUID userId, String walletAddress, L2Credentials creds) {
        WalletCredential row = repository.findByUserId(userId)
                .orElse(new WalletCredential());

        row.setUserId(userId);
        row.setWalletAddress(walletAddress);
        row.setApiKeyEnc(encryption.encrypt(creds.getApiKey()));
        row.setSecretEnc(encryption.encrypt(creds.getSecret()));
        row.setPassphraseEnc(encryption.encrypt(creds.getPassphrase()));

        repository.save(row);
    }
}
