import { readFileSync } from 'node:fs'
import path from 'node:path'
import { defineConfig } from 'vite'
import type { Plugin } from 'vite'
import react from '@vitejs/plugin-react'

// GitHub Pages project sites are served under /<repo-name>/, not the domain root.
// BASE_PATH is passed through the environment (not inline `VAR=... npm run`, which
// breaks on Windows) — real builds/dev/preview leave it unset and get '/' as before.
const base = process.env.BASE_PATH ?? '/'

const MSW_WORKER_FILENAME = 'mockServiceWorker.js'
const MSW_WORKER_SOURCE = path.resolve(__dirname, 'public-demo', MSW_WORKER_FILENAME)

/**
 * Serves/emits the MSW worker script generated by `npx msw init public-demo --no-save`.
 * Deliberately lives outside `public/` (Vite copies everything in `public/` into every
 * `dist/`, including real builds) and is wired up only when `mode === 'demo'`, so the
 * worker script never reaches a real build or a real `npm run dev`.
 */
function demoMswWorkerPlugin(): Plugin {
  return {
    name: 'polypilot-demo-msw-worker',
    configureServer(server) {
      const servedAt = `${base}${MSW_WORKER_FILENAME}`
      server.middlewares.use((req, res, next) => {
        if (req.url?.split('?')[0] !== servedAt) {
          next()
          return
        }
        res.setHeader('Content-Type', 'application/javascript')
        res.setHeader('Service-Worker-Allowed', base)
        res.end(readFileSync(MSW_WORKER_SOURCE))
      })
    },
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: MSW_WORKER_FILENAME,
        source: readFileSync(MSW_WORKER_SOURCE),
      })
    },
    // Requirement: "no request leaves the origin" in demo mode — index.html's Google Fonts
    // <link> tags are real, unrelated-to-demo markup (left untouched for real builds/dev), so
    // stripping them here rather than editing index.html keeps that file's only permitted-edit
    // surface (main.tsx, vite.config.ts, ...) intact. Demo falls back to system fonts.
    transformIndexHtml(html) {
      return html
        .replace(/\s*<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com"[^>]*\/?>\n?/, '')
        .replace(/\s*<link\s+href="https:\/\/fonts\.googleapis\.com[^"]*"\s+rel="stylesheet"\s*\/?>\n?/, '')
    },
  }
}

// Whole-file, drop-in replacements for demo mode, keyed to the exact real file path so only
// `mode === 'demo'` resolves through them — everything else (real dev/build/preview) imports the
// real module untouched. Each replacement exports the same names/signatures as the file it
// replaces (see the files under src/demo/auth/ for the parity proof). No wagmi/viem hook call
// survives in demo mode: SiweLoginPanel no longer uses wagmi at all, and wagmiConfig itself (still
// referenced by main.tsx's WagmiProvider) is swapped for a config with no connectors and
// discovery disabled, so a real wallet extension in the visitor's browser is never touched.
// Vite/Rollup aliasing matches against the raw specifier string as written at each import site
// (e.g. `'../../components/auth/LoginForm'`), not the resolved absolute path, and a RegExp
// `find` is applied as `specifier.replace(find, replacement)` — so the match must span the
// *whole* specifier (`^.*...$`), or only the matched tail gets replaced, mangling the rest of
// the string. Each pattern is anchored on a directory segment unique to the real file
// (`components/auth/...`, `wallet/wagmiConfig`) so it can't accidentally match an unrelated
// import ending in the same basename.
function resolveDemoAliases(mode: string) {
  if (mode !== 'demo') return []
  return [
    {
      find: /^.*components\/auth\/SiweLoginPanel(\.tsx)?$/,
      replacement: path.resolve(__dirname, 'src/demo/auth/SiweLoginPanel.tsx'),
    },
    {
      find: /^.*components\/auth\/LoginForm(\.tsx)?$/,
      replacement: path.resolve(__dirname, 'src/demo/auth/LoginForm.tsx'),
    },
    {
      find: /^.*wallet\/wagmiConfig(\.ts)?$/,
      replacement: path.resolve(__dirname, 'src/demo/auth/wagmiConfig.ts'),
    },
  ]
}

export default defineConfig(({ mode }) => ({
  base,
  plugins: [react(), ...(mode === 'demo' ? [demoMswWorkerPlugin()] : [])],
  resolve: {
    alias: resolveDemoAliases(mode),
  },
  server: {
    host: '0.0.0.0',   // expose to Docker port mapping
    port: 5173,
    hmr: {
      clientPort: 5173  // tells the browser which port to use for HMR websocket
    },
    proxy: {
      // auth/admin/wallet controllers keep "/api" baked into their own @RequestMapping,
      // unlike market/schedule below — forward these untouched, no prefix stripping.
      '/api/auth': { target: 'http://orchestrator:8080', changeOrigin: true },
      '/api/admin': { target: 'http://orchestrator:8080', changeOrigin: true },
      '/api/wallet': { target: 'http://orchestrator:8080', changeOrigin: true },
      // All other /api/* calls from the browser are forwarded to the orchestrator
      // inside the Docker network. The browser never talks to it directly.
      '/api': {
        target: 'http://orchestrator:8080',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, '')
      }
    }
  }
}))
