-- =============================================================================
-- PolyPilot — Baseline Schema
--
-- Conventions:
--   • All PKs are UUID (gen_random_uuid()) — portable, no sequence contention
--   • ENUM-like columns use VARCHAR + CHECK constraints (easy to extend via ALTER)
--   • JSONB for structured-but-flexible payloads (rule trees, signals, articles)
--   • All timestamps are TIMESTAMPTZ — always store UTC, display in local tz
--   • created_at / updated_at on every mutable entity
-- =============================================================================


-- ---------------------------------------------------------------------------
-- EXTENSIONS
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "btree_gin";  -- GIN indexes on JSONB + scalars



CREATE TABLE IF NOT EXISTS roles (
                       id BIGINT generated by default as identity primary key,
                       role_name VARCHAR(255) not null unique

);


-- users holds identity-agnostic account state only. Login credentials
-- (email + password, wallet address, …) live in user_identities so an account
-- can carry more than one sign-in method.
CREATE TABLE IF NOT EXISTS users (
                       id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
                       role_id         BIGINT       NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
                       display_name    VARCHAR(255),
                       enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
                       created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                       updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);


-- One row per sign-in method attached to a user.
--   type       = 'PASSWORD' | 'ETH_WALLET'
--   identifier = email (lower-cased) for PASSWORD, wallet address (lower, 0x…) for ETH_WALLET
--   secret     = bcrypt hash for PASSWORD, NULL for ETH_WALLET (proof is the SIWE signature)
CREATE TABLE IF NOT EXISTS user_identities (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type         VARCHAR(32) NOT NULL,          -- 'PASSWORD' | 'ETH_WALLET'
    identifier   VARCHAR(255) NOT NULL,         -- email (lower) | address (lower, 0x…)
    secret       VARCHAR(255),                  -- bcrypt hash for PASSWORD, NULL for ETH_WALLET
    verified_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ,
    CONSTRAINT uq_identity UNIQUE (type, identifier)
);

CREATE INDEX IF NOT EXISTS ix_user_identities_user
    ON user_identities(user_id);


-- Multi-wallet support is deferred. The current design is intentionally 1:1 —
-- one wallet per user, enforced by user_id UNIQUE below. Revisit (drop the
-- UNIQUE, add a "label"/"is_primary" column) only when a user genuinely needs
-- to connect more than one Polymarket wallet.
CREATE TABLE IF NOT EXISTS wallet_credentials (
                                    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                    user_id         UUID NOT NULL UNIQUE REFERENCES users(id),
                                    wallet_address  VARCHAR(255) NOT NULL,
                                    api_key_enc     TEXT NOT NULL,
                                    secret_enc      TEXT NOT NULL,
                                    passphrase_enc  TEXT NOT NULL,
                                    connected_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE wallet_credentials IS 'Encrypted Polymarket L2 credentials. Multi-wallet support is deferred: the design stays 1:1 with users via the user_id UNIQUE constraint.';


-- =============================================================================
-- 2. MARKETS
--    Local cache of Polymarket markets, synced via the Gamma API on a schedule.
--    Not a live view — prices here are stale by design; live prices come from
--    the WebSocket feed at trade time. The dashboard reads from this table.
--
--    series.tracked is the gate: only markets that belong to a tracked series
--    are synced and evaluated by the strategy engine. This is what prevents the
--    bot from iterating over all ~10k markets.
-- =============================================================================

CREATE TABLE IF NOT EXISTS job_schedule (
    job_name        VARCHAR(100) PRIMARY KEY,
    cron_expression VARCHAR(100) NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------------
-- SHEDLOCK — leased, TTL'd lock used to guard scheduled strategy evaluations.
--   Standard ShedLock JDBC schema (net.javacrumbs.shedlock), not a custom
--   table: column names/types are exactly what shedlock-provider-jdbc-template
--   expects. A row's lock_until is a self-expiring lease — if the instance
--   holding it dies mid-run, the row simply ages out instead of wedging the
--   next scheduled run forever, which is what a hand-rolled row lock would
--   need extra bookkeeping to achieve. Also the seam that keeps this safe if
--   the orchestrator ever runs as more than one instance.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS shedlock (
    name       VARCHAR(64)  NOT NULL PRIMARY KEY,
    lock_until TIMESTAMP    NOT NULL,
    locked_at  TIMESTAMP    NOT NULL,
    locked_by  VARCHAR(255) NOT NULL
);


-- ---------------------------------------------------------------------------
-- REFERENCE DATA — ticker / timeframe
--   DB-backed vocabularies for the ohlc-sync job (previously in application.yml).
--   Add or disable a row to change what gets synced; no redeploy. Managed
--   directly in the DB for now — no CRUD API.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ticker (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol         VARCHAR(20) NOT NULL UNIQUE,        -- canonical short symbol: 'BTC','ETH'
    binance_symbol VARCHAR(20) NOT NULL,               -- Binance Spot pair: 'BTCUSDT'
    display_name   VARCHAR(60) NOT NULL,               -- 'Bitcoin'
    base_asset     VARCHAR(20) NOT NULL,               -- 'BTC'
    quote_asset    VARCHAR(20) NOT NULL DEFAULT 'USDT',
    sort_order     INT         NOT NULL DEFAULT 0,
    enabled        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS timeframe (
    code           VARCHAR(8)  PRIMARY KEY,            -- Binance interval code: '1m','1h','1M'
    label          VARCHAR(40) NOT NULL,               -- '1 minute'
    milliseconds   BIGINT,                             -- nominal candle length; NULL for calendar-based ('1M')
    sort_order     INT         NOT NULL DEFAULT 0,
    enabled        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS series (
                        id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
                        polymarket_id                  TEXT        NOT NULL,
                        ticker                  TEXT        NOT NULL UNIQUE,
                        slug                    TEXT        NOT NULL,
                        title                   TEXT        NOT NULL,
                        recurrence                TEXT        NOT NULL,
                        series_type               VARCHAR(50),
                        tracked                   BOOLEAN     NOT NULL DEFAULT FALSE,
                        ticker_id                 UUID        REFERENCES ticker(id)   -- asset this series tracks; NULL until set
);

CREATE TABLE IF NOT EXISTS markets (
                         id                      TEXT        PRIMARY KEY,
                         polymarket_condition_id VARCHAR(255) NOT NULL UNIQUE, -- Polymarket hex ID, used by CLOB

                         question                TEXT         NOT NULL,
                         category                VARCHAR(100),

                         status                  VARCHAR(50)  NOT NULL DEFAULT 'OPEN'
                             CHECK (status IN ('OPEN', 'CLOSED', 'RESOLVED', 'CANCELLED')),

                         up_price                NUMERIC(6,4)
                             CHECK (up_price BETWEEN 0 AND 1),

                         down_price              NUMERIC(6,4)
                             CHECK (down_price BETWEEN 0 AND 1),

                         volume_24h              NUMERIC(18,4),
                         liquidity               NUMERIC(18,4),

                         resolution_date         TIMESTAMPTZ, -- when the market settles

                         outcome                 VARCHAR(10)
                             CHECK (outcome IN ('UP', 'DOWN', NULL)),

                         last_synced_at          TIMESTAMPTZ,

                         created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                         updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

                         series_id                UUID         NOT NULL,

                         CONSTRAINT fk_market_event
                             FOREIGN KEY (series_id)
                                 REFERENCES series(id)
);

CREATE INDEX IF NOT EXISTS idx_markets_status   ON markets (status);



-- =============================================================================
-- 3. STRATEGIES
--    A strategy is a named, configurable unit of trading logic.
--    Each strategy has its own schedule, risk limits, and rule tree.
--
--    rule_tree (JSONB): AND/OR nested condition tree evaluated by
--    StrategyEvaluator.java. Example:
--      {
--        "operator": "AND",
--        "conditions": [
--          { "field": "up_price", "op": "lt", "value": 0.30 },
--          { "operator": "OR",
--            "conditions": [
--              { "field": "sentiment.confidence", "op": "gt", "value": 0.8 },
--              { "field": "volume_24h",            "op": "gt", "value": 50000 }
--            ]
--          }
--        ]
--      }
--
--    dry_run: per-strategy flag. A strategy can be in dry-run while another
--    trades live — allows safe parallel testing of new strategies.
-- =============================================================================

CREATE TABLE IF NOT EXISTS strategies (
                            id                   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
                            user_id              UUID         NOT NULL REFERENCES users (id),
                            name                 VARCHAR(255) NOT NULL,
                            description          TEXT,
                            enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
                            dry_run              BOOLEAN      NOT NULL DEFAULT TRUE,   -- safe default
                            cron_expression      VARCHAR(100) NOT NULL DEFAULT '0 */5 * * * *',  -- every 5 min
                            series_id            UUID         NOT NULL REFERENCES series (id),  -- evaluation target: follows this series's current OPEN market + linked asset
                            token_side           VARCHAR(3)   NOT NULL DEFAULT 'YES'
                                CHECK (token_side IN ('YES', 'NO')),
                            order_type           VARCHAR(10)  NOT NULL DEFAULT 'GTC'
                                CHECK (order_type IN ('GTC', 'GTD', 'FOK', 'FAK')),
                            max_bet_size         NUMERIC(18,4) NOT NULL DEFAULT 10.0,   -- USDC
                            max_daily_exposure   NUMERIC(18,4) NOT NULL DEFAULT 100.0,  -- USDC
                            stop_loss_threshold  NUMERIC(6,4)  CHECK (stop_loss_threshold BETWEEN 0 AND 1),
                            rule_tree            JSONB         NOT NULL,
                            created_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
                            updated_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
                            deleted_at           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_strategies_enabled ON strategies (enabled) WHERE enabled = TRUE;
CREATE INDEX IF NOT EXISTS idx_strategies_rule_tree ON strategies USING GIN (rule_tree);
CREATE INDEX IF NOT EXISTS idx_strategies_user_id ON strategies (user_id);
CREATE INDEX IF NOT EXISTS idx_strategies_series_id ON strategies (series_id);
-- Partial, not a table-level UNIQUE(user_id, name): a soft-deleted strategy must not block the
-- same user from reusing its name, so only active (deleted_at IS NULL) rows are constrained.
CREATE UNIQUE INDEX IF NOT EXISTS uq_strategies_user_id_name_active
    ON strategies (user_id, name) WHERE deleted_at IS NULL;


-- =============================================================================
-- 4. ORDERS
--    Every order the engine considers placing — real or dry-run — gets a row.
--    is_dry_run is denormalised from strategies deliberately: a strategy can
--    toggle between modes over time, and you need to query "all real orders
--    in March" without joining back to the strategy's current state.
--
--    external_order_id: null for dry-run or pre-submission failures.
--    Non-null means the order reached Polymarket's CLOB infrastructure.
--
--    size_requested vs size_filled: GTC/FAK orders can partially fill.
--    Tracking both lets you measure slippage and fill rate over time.
-- =============================================================================

    CREATE TABLE IF NOT EXISTS orders (
                        id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
                        strategy_id       UUID         NOT NULL REFERENCES strategies (id),
                        market_id         TEXT         NOT NULL REFERENCES markets (id),
                        user_id           UUID         NOT NULL REFERENCES users (id),
                        external_order_id VARCHAR(255) UNIQUE,        -- CLOB order ID; NULL if dry-run
                        token_side        VARCHAR(3)   NOT NULL CHECK (token_side IN ('YES', 'NO')),
                        order_type        VARCHAR(10)  NOT NULL CHECK (order_type IN ('GTC', 'GTD', 'FOK', 'FAK')),
                        size_requested    NUMERIC(18,4) NOT NULL,
                        size_filled       NUMERIC(18,4) NOT NULL DEFAULT 0,
                        price             NUMERIC(6,4)  NOT NULL,      -- limit price at submission
                        status            VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN (
                                              'PENDING', 'OPEN', 'FILLED',
                                              'PARTIALLY_FILLED', 'CANCELLED', 'FAILED'
                                )),
                        is_dry_run        BOOLEAN       NOT NULL DEFAULT TRUE,
                        failure_reason    TEXT,                         -- populated when status = 'FAILED'
                        placed_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
                        filled_at         TIMESTAMPTZ,
                        created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
                        updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- RiskGuard hot path: daily exposure check
CREATE INDEX IF NOT EXISTS idx_orders_strategy_date ON orders (strategy_id, placed_at DESC)
    WHERE is_dry_run = FALSE;

-- Dashboard: recent orders per market
CREATE INDEX IF NOT EXISTS idx_orders_market ON orders (market_id, placed_at DESC);

-- Polling: find all non-terminal orders to sync status from CLOB
CREATE INDEX IF NOT EXISTS idx_orders_open ON orders (status)
    WHERE status IN ('PENDING', 'OPEN', 'PARTIALLY_FILLED');


-- =============================================================================
-- 5. POSITIONS
--    Net holding after one or more order fills.
--    One position row per (user, market, token_side, is_dry_run) group — a
--    position is OPEN until fully sold or market resolves.
--
--    avg_entry_price: recalculated on every fill using weighted average.
--      new_avg = (old_size * old_avg + fill_size * fill_price)
--                / (old_size + fill_size)
--
--    unrealized_pnl: (current_price - avg_entry_price) * size
--      Written by the price-sync scheduler; not a computed column because
--      current_price comes from the WebSocket cache, not a join.
-- =============================================================================

CREATE TABLE IF NOT EXISTS positions (
                           id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
                           market_id         TEXT        NOT NULL REFERENCES markets (id),
                           user_id           UUID        NOT NULL REFERENCES users (id),
                           token_side        VARCHAR(3)  NOT NULL CHECK (token_side IN ('YES', 'NO')),
                           size              NUMERIC(18,4) NOT NULL DEFAULT 0,
                           avg_entry_price   NUMERIC(6,4)  NOT NULL,
                           current_price     NUMERIC(6,4),
                           unrealized_pnl    NUMERIC(18,4),
                           realized_pnl      NUMERIC(18,4) NOT NULL DEFAULT 0,
                           status            VARCHAR(20)   NOT NULL DEFAULT 'OPEN'
                               CHECK (status IN ('OPEN', 'CLOSED', 'RESOLVED')),
                           is_dry_run        BOOLEAN       NOT NULL DEFAULT TRUE,
                           opened_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
                           closed_at         TIMESTAMPTZ,
                           created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
                           updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    -- one live position per (user, market, side, mode)
                           CONSTRAINT uq_position_key UNIQUE (user_id, market_id, token_side, is_dry_run, status)
);

CREATE INDEX IF NOT EXISTS idx_positions_user_open ON positions (user_id, status)
    WHERE status = 'OPEN';
CREATE INDEX IF NOT EXISTS idx_positions_market ON positions (market_id);




-- =============================================================================
-- 6. SENTIMENT_SCORES
--    Full time-series: one row per LangGraph analysis run per market.
--    The dashboard reads the latest row; the history enables drift analysis
--    and backtesting signal quality.
--
--    article_count: a confidence of 0.9 from 1 article vs. 20 articles is
--    very different. Stored explicitly for signal quality auditing.
--
--    raw_response: full LLM output preserved verbatim. Essential for prompt
--    iteration and debugging unexpected scores.
-- =============================================================================

CREATE TABLE IF NOT EXISTS sentiment_scores (
                                  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
                                  market_id     TEXT        NOT NULL REFERENCES markets (id),
                                  sentiment     VARCHAR(10) NOT NULL CHECK (sentiment IN ('BULLISH', 'BEARISH', 'NEUTRAL')),
                                  confidence    NUMERIC(4,3) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
                                  reasoning     TEXT,                      -- LLM's explanation of the score
                                  model_used    VARCHAR(100) NOT NULL,     -- e.g. 'claude-3-5-sonnet-20241022'
                                  article_count INTEGER      NOT NULL DEFAULT 0,
                                  raw_response  JSONB,                     -- verbatim LLM output for debugging
                                  scored_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  sentiment_scores               IS 'Time-series sentiment scores from the LangGraph AI agent.';
COMMENT ON COLUMN sentiment_scores.confidence    IS '0.0–1.0. Strategy rules gate on this value directly.';
COMMENT ON COLUMN sentiment_scores.article_count IS 'Articles analysed. Low count = low signal reliability.';
COMMENT ON COLUMN sentiment_scores.raw_response  IS 'Full LLM output. Never discard — invaluable for prompt tuning.';

-- Primary query pattern: latest score per market
CREATE INDEX IF NOT EXISTS idx_sentiment_market_time ON sentiment_scores (market_id, scored_at DESC);


-- =============================================================================
-- 7. NEWS_SUMMARIES
--    Separate from sentiment_scores: they're produced in the same LangGraph
--    run but serve different consumers (dashboard reader vs. trading engine)
--    and have different freshness requirements.
--
--    expires_at: the scheduler checks this before triggering a new LLM call.
--    If NOW() < expires_at, skip — primary cost-control for LLM API usage.
--
--    articles (JSONB): array of { url, title, published_at, source } objects.
--    Stored so the dashboard can render source links, and so you can audit
--    exactly what the LLM read when producing the summary.
-- =============================================================================

CREATE TABLE IF NOT EXISTS news_summaries (
                                id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
                                market_id   TEXT    NOT NULL REFERENCES markets (id),
                                summary     TEXT    NOT NULL,
                                articles    JSONB   NOT NULL DEFAULT '[]',   -- [{url, title, published_at, source}]
                                model_used  VARCHAR(100) NOT NULL,
                                fetched_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                                expires_at  TIMESTAMPTZ  NOT NULL            -- scheduler skips re-fetch before this
);

COMMENT ON TABLE  news_summaries            IS 'LLM-generated news summaries per market. Separate lifetime from sentiment.';
COMMENT ON COLUMN news_summaries.expires_at IS 'Scheduler skips LLM call if NOW() < expires_at. Primary cost control.';
COMMENT ON COLUMN news_summaries.articles   IS 'Source articles as [{url,title,published_at,source}]. Rendered in dashboard.';

-- Latest valid summary per market
CREATE INDEX IF NOT EXISTS idx_news_market_expiry ON news_summaries (market_id, expires_at DESC);


-- =============================================================================
-- 8. PRICE_SNAPSHOTS
--    Time-series of market prices written by the scheduler every N minutes.
--    Powers two things:
--      1. Probability history chart on the dashboard
--      2. Backtesting: "what was the price when a strategy would have fired?"
--
--    Note: (market_id, snapshot_at) is a natural composite PK but UUID is
--    used for consistency. Add PARTITION BY RANGE (snapshot_at) monthly
--    if this table grows large.
-- =============================================================================

CREATE TABLE IF NOT EXISTS price_snapshots (
                                 id           UUID     PRIMARY KEY DEFAULT gen_random_uuid(),
                                 market_id    TEXT     NOT NULL REFERENCES markets (id),
                                 up_price    NUMERIC(6,4) CHECK (up_price BETWEEN 0 AND 1),
                                 down_price     NUMERIC(6,4) CHECK (down_price  BETWEEN 0 AND 1),
                                 volume_24h   NUMERIC(18,4),
                                 liquidity    NUMERIC(18,4),
                                 snapshot_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE price_snapshots IS 'Periodic price snapshots. Powers history charts and backtesting.';

-- Range queries: prices for market X between time A and B
CREATE INDEX IF NOT EXISTS idx_price_snapshots_market_time ON price_snapshots (market_id, snapshot_at DESC);


-- =============================================================================
-- 9. AUDIT_LOGS
--    The most important table for a trading bot. Every engine decision writes
--    a row here — order placed, order skipped, risk blocked, dry-run trade.
--
--    action: machine-readable event type for filtering/grouping in the dashboard.
--
--    signals (JSONB): snapshot of every input value at decision time:
--      {
--        "up_price": 0.27,
--        "sentiment": "BULLISH",
--        "confidence": 0.91,
--        "daily_exposure_used": 45.00,
--        "rule_evaluation": [
--          { "field": "up_price", "op": "lt", "value": 0.30, "result": true },
--          { "field": "sentiment.confidence", "op": "gt", "value": 0.8, "result": true }
--        ]
--      }
--    Even if the market moves later, you can reconstruct exactly what the
--    engine saw and why it acted as it did. This is the reasoning trail.
-- =============================================================================

CREATE TABLE IF NOT EXISTS audit_logs (
                            id           UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
                            strategy_id  UUID    REFERENCES strategies (id),
                            market_id    TEXT    REFERENCES markets (id),
                            order_id     UUID    REFERENCES orders (id),   -- NULL when action = ORDER_SKIPPED
                            user_id      UUID    NOT NULL REFERENCES users (id),
                            action       VARCHAR(50) NOT NULL
                                CHECK (action IN (
                                'STRATEGY_EVALUATED',
                                'ORDER_PLACED',
                                'ORDER_SKIPPED',
                                'RISK_BLOCKED',
                                'DRY_RUN_ORDER',
                                'SIGNAL_RECEIVED',
                                'MARKET_RESOLVED',
                                'POSITION_OPENED',
                                'POSITION_CLOSED',
                                'ALERT_SENT'
                                )),
    is_dry_run   BOOLEAN     NOT NULL DEFAULT TRUE,
    signals      JSONB,                 -- full snapshot of engine inputs at decision time
    reasoning    TEXT,                  -- human-readable explanation of the decision
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Dashboard: recent decisions for a strategy
CREATE INDEX IF NOT EXISTS idx_audit_strategy_time ON audit_logs (strategy_id, created_at DESC);

-- Debugging: all decisions for a specific market
CREATE INDEX IF NOT EXISTS idx_audit_market_time ON audit_logs (market_id, created_at DESC);

-- Filter by action type across all strategies
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs (action, created_at DESC);

-- GIN index for querying inside the signals JSONB
CREATE INDEX IF NOT EXISTS idx_audit_signals ON audit_logs USING GIN (signals);


-- =============================================================================
-- 10. ALERTS
--     Records every outbound notification with its delivery status.
--     Storing alerts in the DB enables:
--       - Replay of failed deliveries
--       - Audit of what was sent and when
--       - Deduplication (check for recent SENT alert before sending again)
--
--     channel: 'EMAIL' | 'WEBHOOK' — add 'SLACK', 'TELEGRAM' later freely.
--     payload: channel-specific body (email HTML, webhook JSON, etc.)
-- =============================================================================

CREATE TABLE IF NOT EXISTS alerts (
                        id         UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
                        order_id   UUID    REFERENCES orders (id),
                        user_id    UUID    NOT NULL REFERENCES users (id),
                        type       VARCHAR(50)  NOT NULL
                            CHECK (type IN (
                                            'ORDER_PLACED', 'ORDER_FILLED', 'ORDER_FAILED',
                                            'RISK_LIMIT_HIT', 'POSITION_CLOSED', 'MARKET_RESOLVED'
                                )),
                        channel    VARCHAR(20)  NOT NULL CHECK (channel IN ('EMAIL', 'WEBHOOK')),
                        payload    JSONB        NOT NULL DEFAULT '{}',
                        status     VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
                        error      TEXT,                   -- populated on delivery failure
                        sent_at    TIMESTAMPTZ,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts (status) WHERE status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_alerts_user   ON alerts (user_id, created_at DESC);


-- =============================================================================
-- 11. INDICATOR CATALOG
--     Seed-owned reference data: the technical indicators a user picks from when
--     assembling a strategy, plus each indicator's configurable parameters and
--     its computed outputs. Read-only at runtime (GET /api/indicators); it grows
--     by migration + seed edit, never by API.
--
--     Shared-vs-specific parameter model (hybrid):
--       • indicator_parameters carries one row per (indicator, parameter) — the
--         backbone. Per-indicator defaults / ranges stay local and obvious.
--       • universal_parameters factors out ONLY the two genuinely shared enum
--         vocabularies (source, timeframe): identical description AND identical
--         valid-value list everywhere they apply. An indicator_parameters row
--         points at one via universal_key and then inherits its allowed_values;
--         it still supplies its own default_value / required.
--       • `period` looks shared but is NOT — its default (and sometimes range)
--         is per-indicator — so it stays a plain local row, never universal.
--
--     Cross-field conventions (fast_period < slow_period, overbought > oversold)
--     are advisory text in the parameter description only. No DB-level CHECK and
--     no Java validation here — that enforcement belongs to strategy-save
--     validation in a later task.
-- =============================================================================

CREATE TABLE IF NOT EXISTS indicators (
    id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    key            VARCHAR(40)  NOT NULL UNIQUE,          -- 'sma','ema','rsi','macd','atr','volume_ma'
    name           VARCHAR(120) NOT NULL,                 -- 'Simple Moving Average'
    abbreviation   VARCHAR(20)  NOT NULL,                 -- 'SMA'  (Volume MA -> 'Vol MA')
    description    TEXT         NOT NULL,
    category       VARCHAR(20)  NOT NULL
                   CHECK (category IN ('TREND', 'MOMENTUM', 'VOLATILITY', 'VOLUME')),
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,     -- hide without deleting
    display_order  INT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS universal_parameters (
    key            VARCHAR(40)  PRIMARY KEY,              -- 'source','timeframe'
    name           VARCHAR(120) NOT NULL,
    description    TEXT         NOT NULL,
    data_type      VARCHAR(20)  NOT NULL CHECK (data_type IN ('ENUM')),
    allowed_values JSONB        NOT NULL,                 -- ["open","high","low","close","hl2","hlc3","ohlc4"]
    default_value  TEXT,                                  -- 'close' for source; NULL for timeframe
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS indicator_parameters (
    id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    indicator_id   UUID         NOT NULL REFERENCES indicators(id) ON DELETE CASCADE,
    key            VARCHAR(40)  NOT NULL,                 -- 'period','fast_period','overbought_level','source','timeframe'
    name           VARCHAR(120) NOT NULL,
    description    TEXT         NOT NULL,
    data_type      VARCHAR(20)  NOT NULL
                   CHECK (data_type IN ('INTEGER', 'NUMBER', 'ENUM')),
    universal_key  VARCHAR(40)  REFERENCES universal_parameters(key),   -- set => inherits allowed_values
    constraints    JSONB        NOT NULL DEFAULT '{}',    -- {min,max,step} | {values:[...]} ; ignored when universal_key set
    default_value  TEXT,                                  -- per-indicator default; NULL when none (e.g. timeframe)
    required       BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order  INT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_indicator_param UNIQUE (indicator_id, key)
);

CREATE TABLE IF NOT EXISTS indicator_outputs (
    id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    indicator_id   UUID         NOT NULL REFERENCES indicators(id) ON DELETE CASCADE,
    key            VARCHAR(40)  NOT NULL,                 -- 'value' | 'macd' | 'signal' | 'histogram'
    name           VARCHAR(120) NOT NULL,
    description    TEXT         NOT NULL,
    value_scale    VARCHAR(20)  NOT NULL
                   CHECK (value_scale IN ('PRICE', 'OSCILLATOR_0_100', 'UNBOUNDED', 'VOLUME')),
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order  INT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_indicator_output UNIQUE (indicator_id, key)
);

CREATE INDEX IF NOT EXISTS ix_indicator_params_indicator  ON indicator_parameters (indicator_id);
CREATE INDEX IF NOT EXISTS ix_indicator_outputs_indicator ON indicator_outputs (indicator_id);


-- =============================================================================
-- 12. OHLC_CANDLES
--     Binance Spot OHLCV candles, one row per (symbol, timeframe, open_time).
--     Sole writer is the `ohlc-sync` scheduled job (see MarketScheduler); it
--     runs independently of any strategy / indicator / order code — its only
--     downstream contract is this table.
--
--     Closed candles are immutable. Only the newest (still-forming) candle is
--     overwritten on each sync: the upsert's DO UPDATE is guarded by
--     `WHERE ohlc_candles.is_closed = false`, so re-fetching an already-closed
--     candle is a no-op. A candle flips to is_closed = true on the first sync
--     that sees Binance report close_time in the past, and is frozen thereafter.
--
--     Add PARTITION BY RANGE (open_time) monthly if this grows large (same note
--     as price_snapshots).
-- =============================================================================

CREATE TABLE IF NOT EXISTS ohlc_candles (
    symbol      VARCHAR(20)   NOT NULL,          -- 'BTCUSDT'
    timeframe   VARCHAR(8)    NOT NULL,          -- Binance interval code: '1m','1h','1d','1w','1M'
    open_time   TIMESTAMPTZ   NOT NULL,          -- candle open, UTC
    open        NUMERIC(20,8) NOT NULL,
    high        NUMERIC(20,8) NOT NULL,
    low         NUMERIC(20,8) NOT NULL,
    close       NUMERIC(20,8) NOT NULL,
    volume      NUMERIC(30,8) NOT NULL,          -- base-asset volume
    close_time  TIMESTAMPTZ   NOT NULL,          -- candle close, UTC
    is_closed   BOOLEAN       NOT NULL DEFAULT TRUE,
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    PRIMARY KEY (symbol, timeframe, open_time)
);

CREATE INDEX IF NOT EXISTS idx_ohlc_candles_stream_time
    ON ohlc_candles (symbol, timeframe, open_time DESC);

COMMENT ON TABLE ohlc_candles IS
    'Binance OHLCV candles, one row per (symbol, timeframe, open_time). Sole writer is the ohlc-sync job. Closed candles are immutable; the forming candle is overwritten each sync.';


-- =============================================================================
-- UPDATED_AT TRIGGER
-- Automatically update updated_at on every mutable table.
-- =============================================================================

-- CREATE OR REPLACE FUNCTION set_updated_at()
-- RETURNS TRIGGER AS $$
-- BEGIN
--     NEW.updated_at = NOW();
-- RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;
--
-- CREATE TRIGGER trg_users_updated_at
--     BEFORE UPDATE ON users
--     FOR EACH ROW EXECUTE FUNCTION set_updated_at();
--
-- CREATE TRIGGER trg_markets_updated_at
--     BEFORE UPDATE ON markets
--     FOR EACH ROW EXECUTE FUNCTION set_updated_at();
--
-- CREATE TRIGGER trg_strategies_updated_at
--     BEFORE UPDATE ON strategies
--     FOR EACH ROW EXECUTE FUNCTION set_updated_at();
--
-- CREATE TRIGGER trg_orders_updated_at
--     BEFORE UPDATE ON orders
--     FOR EACH ROW EXECUTE FUNCTION set_updated_at();
--
-- CREATE TRIGGER trg_positions_updated_at
--     BEFORE UPDATE ON positions
--     FOR EACH ROW EXECUTE FUNCTION set_updated_at();